language: java
install: true
os: linux
dist: bionic
jdk:
  - openjdk14
addons:
  apt:
    update: true
  chrome: stable
script:
  - ./gradlew build --scan -s
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
stages:
  - compile
  - test
  - name: deploy
    if: branch = master